# Site settings
title: A blog about lorem ipsum dolor sit amet
description: My heart beats for data.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Thorben
user_description: My heart beats for data.
user_title: Applied Computer Science Student

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
